version: '0.2'

services:
  db:
    image: 'postgres:16-alpine'
    volumes:
      - 'postgresql-data-shower-thoughts:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=${SERVICE_USER_POSTGRES}
      - POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}
      - POSTGRES_DB=data_database
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'
      interval: 5s
      timeout: 20s
      retries: 10

  data_service:
    build:
      context: ./data
      dockerfile: Dockerfile
    container_name: data_service
    environment:
      - url=jdbc:postgres://$SERVICE_USER_POSTGRES:$SERVICE_PASSWORD_POSTGRES@postgresql:5432/$POSTGRES_DB
      - user=${SERVICE_USER_POSTGRES}
      - password=${SERVICE_PASSWORD_POSTGRES}
    depends_on:
      - db
  web_service:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web_service
    environment:
      - url=jdbc:postgres://$SERVICE_USER_POSTGRES:$SERVICE_PASSWORD_POSTGRES@postgresql:5432/$POSTGRES_DB
      - user=${SERVICE_USER_POSTGRES}
      - password=${SERVICE_PASSWORD_POSTGRES}
    depends_on:
      - db
      - data_service
    ports:
      - "8027:8027"

volumes:
  postgres_data:
